export default Language = {
    signInButtonText: 'Sign in',
    signUpButtonText: 'Sign up',
    forgotText: 'Forgot Password ?',
    fullname: 'Full name',
    email: 'Email',
    password: 'Password',
    phonenumber: 'Phone number',
    confirmPassword: 'Confirm Password',
    privacyAccept: 'By clicking on sign in you automatically accept our ',
    privacyDetails:
      'Terms of Service, Privacy Policy, and our default notification Settings.',
    location: 'Location',
    myLocation: 'My Location',
    rabat: '(Rabat)',
    world: 'Wherever in the world',
    jobs: 'Jobs',
    jobsSelecion: 'Every job',
    agefilter: 'Age filter',
    age: '21-35',
    awesome: 'Awesome!',
    emailSent: 'An email was sent to you ',
    confirmEmail: 'please confirm to continue.',
    continue: 'Continue',
    resend: 'Resend the email',
    profileCompleted: 'Your profile was completed',
    discoverToContinue: 'click discover to continue.',
    discover: 'Discover',
    buy: 'Buy 10 Superlike',
    buyDetail:
      "Regular payment. Cancel anytime. Payment will be charged to your iTunes account at confirmation of purchase. Your subscription renews automatically unless auto-renewal is turned off at least 24 hours before the end of the current period. Your account will be charged for renewal within 24-hours prior to the end of the current period. You can manage your subscription and turn off auto-renewal by going to your iTunes and App Store account settings after purchase. All personal data is handled under the terms and conditions of Naughty Date's privacy policy. More details here",
    LifeGoal: 'Life goal',
    Friendship: 'Friendship',
    SeriousRelationship: 'Serious relationship',
    Marriage: 'Marriage',
    pushNotification: 'Push Notification',
    likes: 'Likes',
    messages: 'Messages',
    utilisateurs: 'utilisateurs en linge',
    inAppNotifications: 'in-app Notifications',
    userName: 'Stephen Conner',
    subName: 'MArrakech',
    editProfile: 'Edit Profile',
    premium: 'Premium',
    user: 'Username',
    gender: 'Gender',
    notification: 'Notification',
    emailAccount: 'name@email.com',
    logout: 'Log out',
    deleteAccount: 'Delete Account',
    help: 'Help and Assistance',
    community: 'Community',
    legalMentions: 'Legal Mentions',
    justAge: 26,
    userInfo:
      '3 years of experience in the health sector including 5 years as Business developer and 4 years as Business unit manager ',
    manger: 'Business Unit Manager',
    experience: '3 years of experience',
    marrakech: 'Marrakech',
    university: 'Harvard University  ',
    lifeGoal: 'Life Goal: Marriage',
    about: 'About',
    about_details:
      '3 years of experience in the health sector including5 years as Business developer and 4 yearsas Business unit manager ',
    information: 'Information',
    height: 'Height:',
    weight: 'Weight:',
    relationshipstatus: 'Relationship status:',
    dateofBirth: 'Date of Birth:',
    country: 'Country:',
    city: 'City:',
    levelofstudies: 'Level of studies:',
    currentjob: 'Current Job:',
    interests: 'Interests',
    guitar: 'Guitar',
    music: 'Music',
    fishing: 'Fishing',
    swimming: 'swimming',
    book: 'Book',
    dancing: 'Dancing',
    spokenLanguage: 'Spoken Language',
    french: 'French',
    anglais: 'Anglais',
    arabic: 'Arabic',
    messages: 'Messages',
    newMatches: 'New Matches',
    typeamessage: 'Type a message...',
    discover: 'Discover',
    chat: 'Chat',
    soyez: 'Soyez gentil et brisez la glace',
    envoyer: 'Envoyer un messagea Clayton Roy pour',
    commencer: 'commencer a la connailtre?',
    dites: 'Dites hello ...',
    username: 'Username*',
    gender: 'Gender*',
    dob: 'Date of Birth*',
    country: 'Country*',
    city: 'City*',
    LOS: 'Level of study',
    job: 'Job',
    height: 'Height',
    bodyShape: 'Body shape',
    intersts: 'Intersts',
    description: 'Description*',
    languages: 'Languages',
    mandatoryCases: '*Mandatory cases',
    apply: 'Apply',
    filtre: 'Filtre',
    finish: 'Finish',
    subscription: 'Subscription',
    buyText: 'Buy',
    fullName: 'Full Name',
    londonGibson: 'London Gibson',
    next: 'Next',
    enterdetails: 'Enter Details',
    objectives: 'Objectives',
  };
  