export default Language = {
  signInButtonText: "S'identifier'",
  signUpButtonText: "S'inscrire",
  forgotText: 'Mot de passe oublié ?',
  fullname: 'Nom complet',
  email: 'E-mail',
  password: 'Mot de passe',
  phonenumber: 'Numéro de téléphone',
  confirmPassword: 'Confirmez le mot de passe',
  privacyAccept:
    'En cliquant sur vous connecter, vous acceptez automatiquement notre ',
  privacyDetails:
    "Conditions d'utilisation, politique de confidentialité et nos paramètres de notification par défaut.",
  location: 'Lieu',
  myLocation: 'Ma position',
  rabat: '(Rabat)',
  world: 'Partout dans le monde',
  jobs: 'Emplois',
  jobsSelecion: 'Chaque travail',
  agefilter: "Filtre d'âge",
  age: '21-35',
  awesome: 'Impressionnante!',
  emailSent: 'Un e-mail vous a été envoyé',
  confirmEmail: 'veuillez confirmer pour continuer.',
  continue: 'Continuez',
  resend: "Renvoyer l'email",
  profileCompleted: 'Votre profil a été complété',
  discoverToContinue: 'cliquez sur découvrir pour continuer.',
  discover: 'Découvrir',
  buy: 'Acheter 10 Superlike',
  buyDetail:
    "Paiement régulier. Annulez à tout moment. Le paiement sera débité de votre compte iTunes lors de la confirmation de l'achat. Votre abonnement se renouvelle automatiquement sauf si le renouvellement automatique est désactivé au moins 24 heures avant la fin de la période en cours. Votre compte sera facturé pour le renouvellement dans les 24 heures précédant la fin de la période en cours. Vous pouvez gérer votre abonnement et désactiver le renouvellement automatique en accédant aux paramètres de votre compte iTunes et App Store après l'achat. Toutes les données personnelles sont traitées selon les termes et conditions de la politique de confidentialité de Naughty Date. Plus de détails ici",
  LifeGoal: 'Le but de la vie',
  Friendship: 'Relation amicale',
  SeriousRelationship: 'Relation serieuse',
  Marriage: 'Mariage',
  pushNotification: 'Notification push',
  likes: 'Aime',
  messages: 'messages',
  utilisateurs: 'utilisateurs en linge',
  inAppNotifications: "Notifications dans l'application",
  userName: 'Stephen Conner',
  subName: 'MArrakech',
  editProfile: 'Editer le profil',
  premium: 'Prime',
  user: "Nom d'utilisateur",
  gender: 'Le genre',
  notification: 'Notification',
  emailAccount: 'name@email.com',
  logout: 'Se déconnecter',
  deleteAccount: 'Supprimer le compte',
  help: 'Aide et assistance',
  community: 'Communauté',
  legalMentions: 'Mentions légales',
  justAge: 26,
  userInfo:
    "3 ans d'expérience dans le secteur de la santé dont 5 ans en tant que Business developer et 4 ans en tant que Business unit manager",
  manger: 'Business Unit Manager',
  experience: '3 years of experience',
  marrakech: 'Marrakech',
  university: 'Harvard University  ',
  lifeGoal: 'Life Goal: Marriage',
  about: 'About',
  about_details:
    "3 ans d'expérience dans le secteur de la santé dont 5 ans en tant que Business developer et 4 ans en tant que Business unit manager",
  information: 'Informations',
  height: 'Hauteur:',
  weight: 'Poids:',
  relationshipstatus: 'Statut de la relation:',
  dateofBirth: 'Date de naissance:',
  country: 'De campagne:',
  city: 'Ville:',
  levelofstudies: "Niveau d'études:",
  currentjob: 'Travail actuel:',
  interests: 'Intérêts',
  guitar: 'Guitare',
  music: 'Musique',
  fishing: 'Faire de la pêche',
  swimming: 'natation',
  book: 'Livre',
  dancing: 'Dansant',
  spokenLanguage: 'Langue parlée',
  french: 'French',
  anglais: 'Anglais',
  arabic: 'Arabic',
  messages: 'Messages',
  newMatches: 'Nouveaux matchs',
  typeamessage: 'Tapez un message...',
  discover: 'Découvrir',
  chat: 'Discuter',
  soyez: 'Soyez gentil et brisez la glace',
  envoyer: 'Envoyer un messagea Clayton Roy pour',
  commencer: 'commencer a la connailtre?',
  dites: 'Dites hello ...',
  username: "Nom d'utilisateur*",
  gender: 'Le genre*',
  dob: 'Date de naissance*',
  country: 'De campagne*',
  city: 'Ville*',
  LOS: "Niveau d'études",
  job: 'Travail',
  height: 'Hauteur',
  bodyShape: 'Forme du corps',
  intersts: 'Intérêts',
  description: 'Description*',
  languages: 'Languages',
  mandatoryCases: '*Mandatory cases',
  apply: 'Appliquer',
  filtre: 'Filtre',
  finish: 'Finir',
  subscription: 'Abonnement',
  buyText: 'Acheter',
  fullName: 'Nom complet',
  londonGibson: 'London Gibson',
  next: 'Suivant',
  enterdetails: 'Entrez les détails',
  objectives: 'Objectifs',
};
