import {Dimensions} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default Theme = {
  primary: '#00A89B',
  primaryLight: '#00A88F',
  headingColor: '#222B45',
  textColor: '#8F9BB3',
  borderColor: '#EDF1F7',
  accent: '#FF3480',
  textInputColor: '#EFEFEF',
  darkAccent: '#FAE1DB',
  rating: '#FFCC00',
  backgroundColor: '#FFFF',
  accentLight: '#FFC1D8',
  btnRadius: 10,
  white: 'white',
  black: 'black',
  btntextSize: 20,
  boxColor: '#fafafa',
  bold: 'bold',
  searchIcon: '#087556',
  ubuntuRegular: 'Ubuntu-Regular',
  fontFamily: 'Nunito-Regular',
  fontFamilyBold: 'Nunito-Bold',
  fontFamilySemiBold: 'Nunito-SemiBold',
  searchBarBg: '#F3F3F3',
  grey: '#BEBEBE',
  sub: '#B3BAC5',
  lightGrey: 'lightgrey',
  fontColor: '#131313',
  fontColorLight: '#707070',
  profileTextcolor: '#262626',
  border_Radius: 5,
  height: Dimensions.get('window').height,
  width: Dimensions.get('window').width,
  premiumBtn: '#C2272D',
  deleteBtn: '#F50B0B',
  logout: '#9BA7CF',
  heightPer: Dimensions.get('window').height / 100,
  widthPer: Dimensions.get('window').width / 100,
  chip: '#707070',
  shadowColor: '#e8e8e8',
  ratingBackground: '#EFEFF4',
  inputText: '#F7F7F9',
  attendenceFontColor: '#131313',
  cardBackground: '#BEBEBE',
  cartText: 'rgba(0,0,0,0.6)',
  tableColor: '#F7FCFC',
  checkBox: '#83af40',
  blueshBg: '#F8FAFC',
  TextInputBackground: '#B9E7E3',
  duration: '#EBF8F7',
  wp,
  hp,
};
