const Icons = {
  location: require('../assets/icons/location.png'),
  art: require('../assets/icons/art.png'),
  beauty: require('../assets/icons/beauty.png'),
  cam: require('../assets/icons/cam.png'),
  chef: require('../assets/icons/chef.png'),
  dance: require('../assets/icons/dance.png'),
  film: require('../assets/icons/film.png'),
  health: require('../assets/icons/health.png'),
  language: require('../assets/icons/language.png'),
  mic: require('../assets/icons/mic.png'),
  education: require('../assets/icons/education.png'),
  manIcon: require('../assets/Images/manIcon.png'),
  infoIcons: require('../assets/icons/infoIcon.png'),
  triangle: require('../assets/icons/triangle.png'),
  success: require('../assets/icons/success.png'),
  locationGreen: require('../assets/icons/locationGreen.png'),
  infoGreen: require('../assets/icons/greenInfo.png'),
  burgerIcon: require('../assets/icons/burgerIcon.png'),
  menu: require('../assets/icons/menu.png'),
  coupon: require('../assets/icons/coupon.png'),
  greenMenu: require('../assets/icons/greenMenu.png'),
  cart: require('../assets/icons/cart.png'),
  durationIcon: require('../assets/icons/durationIcon.png'),
  dropDownIcon: require('../assets/icons/dropDownIcon.png'),
  backIcon: require('../assets/icons/backIcon.png'),
  backBlIcon: require('../assets/icons/backBlIcon.png'),
  rankIcon: require('../assets/icons/rankIcon.png'),

  reviewIcon: require('../assets/icons/reviewIcon.png'),
  bookingIcon: require('../assets/icons/bookingIcon.png'),
  myClassesIcon: require('../assets/icons/myClassesIcon.png'),
  manu_bar: require('../assets/icons/menu_bar.png'),

  heartIcon: require('../assets/icons/heartIcon.png'),
  shareIcon: require('../assets/icons/shareIcon.png'),
};

export default Icons;
